/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifba.scop.infraestructure.view;

import br.com.ifba.pesquisador.view.AtualizacaoPesquisador;
import br.com.ifba.pesquisador.view.CadastroPesquisador;
import br.com.ifba.scop.patente.view.CentroPatente;
import br.com.ifba.scop.projetopesquisa.view.BuscarProjetoPesquisa;
import br.com.ifba.scop.projetopesquisa.view.CadastrarProjetoPesquisa;

/**
 *
 * @author Lucas
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        lblCadastrar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnCadPesquisa = new javax.swing.JButton();
        btnCadPatente = new javax.swing.JButton();
        lblPesquisar = new javax.swing.JLabel();
        btnCadPesquisador = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastrar.setText("CADASTRAR");
        lblCadastrar.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(lblCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 120, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Pesquisa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 170, 30));

        btnCadPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadPesquisa.setText("Pesquisa");
        btnCadPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 170, 30));

        btnCadPatente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadPatente.setText("Patente");
        btnCadPatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPatenteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 170, 30));

        lblPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setText("PESQUISAR");
        getContentPane().add(lblPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 139, 130, 30));

        btnCadPesquisador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadPesquisador.setText("Pesquisador");
        btnCadPesquisador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPesquisadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadPesquisador, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 170, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Pesquisador");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 170, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Patente");
        jButton7.setPreferredSize(new java.awt.Dimension(70, 23));
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 170, 30));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/scop/infraestructure/view/logo_scop.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 400, 270));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/scop/infraestructure/view/fundo_roxo.png"))); // NOI18N
        lblFundo.setText("lblFundo");
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1060, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AtualizacaoPesquisador atualizarPesquisador = new AtualizacaoPesquisador();
        atualizarPesquisador.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * This method calls patente screen main.
     * @param evt Action Event
     */
    private void btnCadPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPatenteActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false); // invisivel
        //this.getDefaultCloseOperation(); // fechando
        CentroPatente centroPatente = new CentroPatente();
        centroPatente.setVisible(true);
    }//GEN-LAST:event_btnCadPatenteActionPerformed

    private void btnCadPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPesquisaActionPerformed
        // TODO add your handling code here:
        CadastrarProjetoPesquisa cadastrarProjeto = new CadastrarProjetoPesquisa();
        cadastrarProjeto.setVisible(true);
    }//GEN-LAST:event_btnCadPesquisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BuscarProjetoPesquisa buscarProjeto = new BuscarProjetoPesquisa();
        buscarProjeto.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCadPesquisadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPesquisadorActionPerformed
        // TODO add your handling code here:
        CadastroPesquisador cadastrarPesquisador = new CadastroPesquisador();
        cadastrarPesquisador.setVisible(true);
    }//GEN-LAST:event_btnCadPesquisadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadPatente;
    private javax.swing.JButton btnCadPesquisa;
    private javax.swing.JButton btnCadPesquisador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPesquisar;
    // End of variables declaration//GEN-END:variables
}
