/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifba.scop.pesquisador.view;

import br.com.ifba.scop.grupopesquisa.model.GrupoPesquisa;
import br.com.ifba.scop.infraestructure.service.Singleton;
import br.com.ifba.scop.infraestructure.support.StringUtil;
import br.com.ifba.scop.pesquisador.model.Pesquisador;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Cliente
 */
public class CadastroPesquisador extends javax.swing.JFrame {
    
    private final List<GrupoPesquisa> grupos = Singleton.getInstance().getAllGrupoPesquisa();
    /**
     * Creates new form CadastroPesquisador
     */
    public CadastroPesquisador() {
        initComponents();
        lblAviso.setVisible(false);
        
        for(int i = 0; i < this.grupos.size(); i++){
            this.comboxGrupoPesquisa.addItem(this.grupos.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtInstituicao = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtTitulacao = new javax.swing.JTextField();
        txtOrgaoEmissor = new javax.swing.JTextField();
        lblInstituicao = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblTitulacao = new javax.swing.JLabel();
        lblOrgEmissor = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        lblRGdata = new javax.swing.JLabel();
        txtLocacao = new javax.swing.JTextField();
        lblLocacao = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        txtRG = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        comboxGrupoPesquisa = new javax.swing.JComboBox<>();
        lblGrupoPesquisa = new javax.swing.JLabel();
        lblAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de pesquisador - SCOP");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Pesquisador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblRG.setText("RG");

        lblNome.setText("Nome");

        lblCPF.setText("CPF");

        lblEmail.setText("E-mail");

        lblInstituicao.setText("Instituição");

        lblMatricula.setText("Matrícula");

        lblTitulacao.setText("Titulação");

        lblOrgEmissor.setText("Orgão emissor");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());

        lblRGdata.setText("Data de emissão");

        lblLocacao.setText("Locação");

        btnConfirm.setText("Confirmar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        try {
            txtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        comboxGrupoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxGrupoPesquisaActionPerformed(evt);
            }
        });

        lblGrupoPesquisa.setText("Grupo de Pesquisa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome)
                            .addComponent(lblRG)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCPF)
                                    .addComponent(lblEmail)
                                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinner1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblRGdata)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblGrupoPesquisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboxGrupoPesquisa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLocacao)
                            .addComponent(txtLocacao, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtTitulacao, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtOrgaoEmissor, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(lblInstituicao)
                            .addComponent(lblMatricula)
                            .addComponent(lblTitulacao)
                            .addComponent(lblOrgEmissor)
                            .addComponent(txtMatricula))))
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblInstituicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRG)
                    .addComponent(lblMatricula)
                    .addComponent(lblRGdata))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(lblTitulacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(lblOrgEmissor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrgaoEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocacao)
                    .addComponent(lblGrupoPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxGrupoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblAviso.setForeground(new java.awt.Color(255, 0, 0));
        lblAviso.setText("Aviso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblAviso))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(lblAviso)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        // Verificação de campos vazios
        Pesquisador pesquisador = new Pesquisador();
        
        if(validaCampos() == true){
            pesquisador.setCpf(txtCPF.getText());
            pesquisador.setEmail(txtEmail.getText());
            pesquisador.setInstituição(txtInstituicao.getText());
            pesquisador.setLocação(txtLocacao.getText());
            pesquisador.setMatricula(txtMatricula.getText());
            pesquisador.setNome(txtNome.getText());
            pesquisador.setOrgaoEmisor(txtOrgaoEmissor.getText());
            pesquisador.setRg(txtRG.getText());
            pesquisador.setTitulação(txtTitulacao.getText());
            
            if(Singleton.getInstance().savePesquisador(pesquisador) == pesquisador){

                JOptionPane.showMessageDialog(null, "Salvo com sucesso!");

               // Fecha a janela
                this.dispose();

            }else{
                    JOptionPane.showMessageDialog(null, "Erro ao salvar");
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void comboxGrupoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxGrupoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxGrupoPesquisaActionPerformed

    private boolean validaCampos(){
        
        StringUtil util = StringUtil.getInstance();
        
        // Validação de todos os campos ao mesmo tempo
        if(txtNome.getText().equals("") && txtRG.getText().equals("  .   .   -  ")){
            if(txtCPF.getText().equals("   .   .   -  ") && txtEmail.getText().equals("")){
                if(txtInstituicao.getText().equals("") && txtMatricula.getText().equals("")){
                    if (txtTitulacao.getText().equals("") && txtOrgaoEmissor.getText().equals("") && txtLocacao.getText().equals("")){
                        lblNome.setText("Nome*");
                        lblNome.setForeground(Color.red);
                        lblRG.setText("RG*");
                        lblRG.setForeground(Color.red);
                        lblCPF.setText("CPF*");
                        lblCPF.setForeground(Color.red);
                        lblEmail.setText("E-mail*");
                        lblEmail.setForeground(Color.red);
                        lblInstituicao.setText("Instituição*");
                        lblInstituicao.setForeground(Color.red);
                        lblMatricula.setText("Matrícula*");
                        lblMatricula.setForeground(Color.red);
                        lblTitulacao.setText("Titulação*");
                        lblTitulacao.setForeground(Color.red);
                        lblOrgEmissor.setText("Orgão Emissor*");
                        lblOrgEmissor.setForeground(Color.red);
                        lblLocacao.setText("Locação*");
                        lblLocacao.setForeground(Color.red);
                        
                        JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios.", "CAMPOS OBRIGATÓRIOS", JOptionPane.ERROR_MESSAGE);
                        return false;                        
                    }
                }
            }
        }
        
        // Validação dos campos individuais
        // nome
        if(util.isNullOrEmpty(txtNome.getText())){
            lblNome.setText("Nome*");
            lblNome.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
        }else{
            lblNome.setText("Nome");
            lblNome.setForeground(Color.black);
        }
        // Campo RG
        if(util.isNullOrEmpty(txtRG.getText())){
            lblRG.setText("RG*");
            lblRG.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Preencha o campo RG.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
        }else{
            lblRG.setText("RG");
            lblRG.setForeground(Color.black);
        }
        // Campo CPF
        if(util.isNullOrEmpty(txtCPF.getText())){
            lblCPF.setText("CPF*");
            lblCPF.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Preencha o campo CPF.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
        }else{
            lblCPF.setText("CPF");
            lblCPF.setForeground(Color.black);
        }
        // Campo E-mail
        if(util.isNullOrEmpty(txtEmail.getText())){
            lblEmail.setText("E-mail*");
            lblEmail.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Preencha o campo E-mail.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
        }else{
            lblEmail.setText("E-mail");
            lblEmail.setForeground(Color.black);
        }
        
        // Campo Instituição
        if(util.isNullOrEmpty(txtInstituicao.getText())){
            lblInstituicao.setText("Instituição*");
            lblInstituicao.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Preencha o campo Instituição.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
        }else{
            lblInstituicao.setText("Instituição");
            lblInstituicao.setForeground(Color.black);
        }
        
        // Campo Matricula
        if(util.isNullOrEmpty(txtMatricula.getText())){
            lblMatricula.setText("Matrícula*");
            lblMatricula.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Preencha o campo Matrícula.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
        }else{
            lblMatricula.setText("Matríula");
            lblMatricula.setForeground(Color.black);
        }
        
        // Campo Titulação
        
        if(util.isNullOrEmpty(txtTitulacao.getText())){
            lblTitulacao.setText("Titulação*");
            lblTitulacao.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Preencha o campo Titulação.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
        }else{
            lblTitulacao.setText("Titulação");
            lblTitulacao.setForeground(Color.black);
        }
        
        // Campo Orgão Emissor
        if(util.isNullOrEmpty(txtOrgaoEmissor.getText())){
            lblOrgEmissor.setText("Orgão Emissor*");
            lblOrgEmissor.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Preencha o campo Orgão Emissor.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
        }else{
            lblOrgEmissor.setText("Orgão Emissor");
            lblOrgEmissor.setForeground(Color.black);
        }
        
        // Campo Locação
        
        if(util.isNullOrEmpty(txtLocacao.getText())){
            lblLocacao.setText("Locação*");
            lblLocacao.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Preencha o campo Locação.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
        }else{
            lblLocacao.setText("Locação");
            lblLocacao.setForeground(Color.black);
        }
        
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPesquisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPesquisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPesquisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPesquisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPesquisador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<GrupoPesquisa> comboxGrupoPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGrupoPesquisa;
    private javax.swing.JLabel lblInstituicao;
    private javax.swing.JLabel lblLocacao;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblOrgEmissor;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRGdata;
    private javax.swing.JLabel lblTitulacao;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtInstituicao;
    private javax.swing.JTextField txtLocacao;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtOrgaoEmissor;
    private javax.swing.JFormattedTextField txtRG;
    private javax.swing.JTextField txtTitulacao;
    // End of variables declaration//GEN-END:variables
}
