/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifba.scop.grupopesquisa.view;

import br.com.ifba.scop.grupopesquisa.model.GrupoPesquisa;
import br.com.ifba.scop.infraestructure.service.Fachada;
import br.com.ifba.scop.infraestructure.service.IFachada;
import br.com.ifba.scop.infraestructure.support.StringUtil;
import java.awt.Color;
import javax.swing.JOptionPane;



/**
 *
 * @author jonatasfbastos
 */
public class CadastrarGrupoPesquisa extends javax.swing.JFrame {

    GrupoPesquisa grupopesquisa;
    
    
    // Esse contrutor é chamado quando a operação for salvar
    /**
     * Creates new form CadastrarProjetoPesquisa
     */
    public CadastrarGrupoPesquisa() {
        initComponents();
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setToolTipText("Clique aqui para salvar o cadastro");
        lblTelaBusca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTelaBusca.setToolTipText("Clique aqui visualizar grupos de pesquisa");
        this.radioSim.setSelected(true);
        this.radioSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.radioNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.grupopesquisa = new GrupoPesquisa();
    }
    
    // Esse contrutor é chamado quando a operação for aualizar
    public CadastrarGrupoPesquisa(GrupoPesquisa editado) {
        initComponents();
        
        btnCadastrar.setText("Atualizar");
        
        this.grupopesquisa = editado;
        
        this.txtNomeGrupoPesquisa.setText(editado.getNome());
        this.txtAreaConhecimento.setText(editado.getAreaConhecimento());
        this.txtAtividadeGrupoPesquisa.setText(editado.getAtividadeGrupo());
        this.txtPalavraChave.setText(editado.getPalavraChave());
        this.txtResumoAtividades.setText(editado.getResumoAtividades());
        this.radioSim.setSelected(editado.isInfraEstrutura());
        this.radioNao.setSelected(!this.radioSim.isSelected());
        this.txtDescricaoIE.setText(editado.getDescricaoIE());
        this.txtComentariosAdicionais.setText(editado.getComentariosAdicionais());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        grupoBotoes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtAtividadeGrupoPesquisa = new javax.swing.JTextField();
        lblAtividadeGrupoPesquisa = new javax.swing.JLabel();
        lblAreaConhecimento = new javax.swing.JLabel();
        lblNomeGrupoPesquisa = new javax.swing.JLabel();
        lblPalavraChave = new javax.swing.JLabel();
        lblResumoAtividades = new javax.swing.JLabel();
        txtNomeGrupoPesquisa = new javax.swing.JTextField();
        txtAreaConhecimento = new javax.swing.JTextField();
        lblResultadosEsperados = new javax.swing.JLabel();
        lblInfraEstrutura = new javax.swing.JLabel();
        txtDescricaoIE = new javax.swing.JTextField();
        lblDescricaoIE = new javax.swing.JLabel();
        lblComentariosAdicionais = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radioSim = new javax.swing.JRadioButton();
        radioNao = new javax.swing.JRadioButton();
        txtComentariosAdicionais = new javax.swing.JTextField();
        txtResultadosEsperados = new javax.swing.JTextField();
        txtResumoAtividades = new javax.swing.JTextField();
        txtPalavraChave = new javax.swing.JTextField();
        lblTelaBusca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtAtividadeGrupoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 168, 303, 27));

        lblAtividadeGrupoPesquisa.setText("Atividade do Grupo de Pesquisa");
        jPanel1.add(lblAtividadeGrupoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 148, 240, -1));

        lblAreaConhecimento.setText("Área de Conhecimento");
        jPanel1.add(lblAreaConhecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 209, 230, -1));

        lblNomeGrupoPesquisa.setText("Nome do Grupo de Pesquisa");
        jPanel1.add(lblNomeGrupoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 87, 220, 20));

        lblPalavraChave.setText("Palavra-Chave");
        jPanel1.add(lblPalavraChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 240, -1));

        lblResumoAtividades.setText("Resumo de Atividades");
        jPanel1.add(lblResumoAtividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 250, -1));
        jPanel1.add(txtNomeGrupoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 303, 27));
        jPanel1.add(txtAreaConhecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 303, 27));

        lblResultadosEsperados.setText("Resultados Esperados");
        jPanel1.add(lblResultadosEsperados, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 250, -1));

        lblInfraEstrutura.setText("Infra-Estrutura");
        jPanel1.add(lblInfraEstrutura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 90, -1));
        jPanel1.add(txtDescricaoIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 303, 90));

        lblDescricaoIE.setText("Descrição de Infra-Estrutura");
        jPanel1.add(lblDescricaoIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 310, -1));

        lblComentariosAdicionais.setText("Comentários Adicionais");
        jPanel1.add(lblComentariosAdicionais, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 310, -1));

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/scop/projetopesquisa/view/imagens/icon_add.png"))); // NOI18N
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/scop/projetopesquisa/view/imagens/Logo_scop_projeto.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 190, 120));

        grupoBotoes.add(radioSim);
        radioSim.setText("Sim");
        radioSim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioSimItemStateChanged(evt);
            }
        });
        jPanel1.add(radioSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        grupoBotoes.add(radioNao);
        radioNao.setText("Não");
        jPanel1.add(radioNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));
        jPanel1.add(txtComentariosAdicionais, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 303, 90));
        jPanel1.add(txtResultadosEsperados, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 303, 90));
        jPanel1.add(txtResumoAtividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 303, 90));
        jPanel1.add(txtPalavraChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 295, 303, 27));

        lblTelaBusca.setForeground(new java.awt.Color(102, 102, 102));
        lblTelaBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/scop/projetopesquisa/view/imagens/icon_pesquisar.png"))); // NOI18N
        lblTelaBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTelaBuscaMouseClicked(evt);
            }
        });
        jPanel1.add(lblTelaBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/scop/projetopesquisa/view/imagens/fundo_tela_buscarr.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
            
        IFachada fachada = new Fachada();

        // Verifica se o projeto é valido
        if(validaCampos() == true){

            // Atribuindo os dados dos campos aos atributos do objeto
            this.grupopesquisa.setNome(this.txtNomeGrupoPesquisa.getText());
            this.grupopesquisa.setAtividadeGrupo(this.txtAtividadeGrupoPesquisa.getText());
            this.grupopesquisa.setPalavraChave(this.txtPalavraChave.getText());
            this.grupopesquisa.setAreaConhecimento(this.txtAreaConhecimento.getText());
            this.grupopesquisa.setResumoAtividades(this.txtResumoAtividades.getText());
            this.grupopesquisa.setResultadosEsperados(this.txtResultadosEsperados.getText());
            this.grupopesquisa.setInfraEstrutura(this.radioSim.isSelected());
            this.grupopesquisa.setDescricaoIE(this.txtDescricaoIE.getText());
            this.grupopesquisa.setComentariosAdicionais(this.txtComentariosAdicionais.getText());
            
            // Já existe na base. Updade nele!
             if(fachada.getByIdGrupoPesquisa(grupopesquisa.getId()) == grupopesquisa){

                // Atualixzado com sucesso
                if(fachada.updateGrupoPesquisa(grupopesquisa) == grupopesquisa){
                   
                    JOptionPane.showMessageDialog(null, "Editado com sucesso!");

                    // Fecha a janela
                    this.dispose();

                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao editar");
                }

            }else{
                // Ainda não existe na base

                // Salvo com sucesso
                if(fachada.saveGrupoPesquisa(grupopesquisa) == grupopesquisa){

                    JOptionPane.showMessageDialog(null, "Salvo com sucesso!");

                    // Fecha a janela
                    this.dispose();

                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao salvar");
                }
            }
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    // Evento que acontece ao mudar de para "Sim" ou para "Não" os botoẽs radio
    private void radioSimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioSimItemStateChanged
        // TODO add your handling code here:
        this.txtDescricaoIE.setText("");
        this.txtDescricaoIE.setEditable(this.radioSim.isSelected());  
        
        if(!radioSim.isSelected()){
            lblDescricaoIE.setText("Descrição de Infra-Estrutura");
            lblDescricaoIE.setForeground(Color.black);
            txtDescricaoIE.setToolTipText("Não é possível preencher este campo");
        }
    }//GEN-LAST:event_radioSimItemStateChanged

    private void lblTelaBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTelaBuscaMouseClicked
        // TODO add your handling code here:
        new BuscarGrupoPesquisa().setVisible(true);
    }//GEN-LAST:event_lblTelaBuscaMouseClicked

    //valida se todosos campos em conjunto ou individualmente estão preenchidos
   private boolean validaCampos(){
    
    StringUtil util = StringUtil.getInstance();
       
    if(txtNomeGrupoPesquisa.getText().equals("") && txtAtividadeGrupoPesquisa.getText().equals("")){
        if(txtAreaConhecimento.getText().equals("") && txtPalavraChave.getText().equals("")){
            if(txtResultadosEsperados.getText().equals("") && txtComentariosAdicionais.getText().equals("")){
                if(txtResumoAtividades.getText().equals("") && txtDescricaoIE.getText().equals("")){
                    lblNomeGrupoPesquisa.setText("Nome do Grupo de Pesquisa*");
                    lblNomeGrupoPesquisa.setForeground(Color.red);
                    lblAtividadeGrupoPesquisa.setText("Atividade do Grupo de Pesquisa*");
                    lblAtividadeGrupoPesquisa.setForeground(Color.red);
                    lblAreaConhecimento.setText("Área de Conhecimento*");
                    lblAreaConhecimento.setForeground(Color.red);
                    lblPalavraChave.setText("Palavra-Chave*");
                    lblPalavraChave.setForeground(Color.red);
                    lblResultadosEsperados.setText("Resultados Esperados*");
                    lblResultadosEsperados.setForeground(Color.red);
                    lblComentariosAdicionais.setText("Comentários Adicionais*");
                    lblComentariosAdicionais.setForeground(Color.red);
                    lblResumoAtividades.setText("Resumo das Atividades*");
                    lblResumoAtividades.setForeground(Color.red);
                    lblDescricaoIE.setText("Descrição de Infra-Estrutura*");
                    lblDescricaoIE.setForeground(Color.red);
                    
                    JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios.", "CAMPOS OBRIGATÓRIOS", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }
        }
    }
    
    if(util.isNullOrEmpty(txtNomeGrupoPesquisa.getText())){
        lblNomeGrupoPesquisa.setText("Nome do Grupo de Pesquisa*");
        lblNomeGrupoPesquisa.setForeground(Color.red);
           
        JOptionPane.showMessageDialog(null, "Preencha o campo Nome do Grupo de Pesquisa.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
        return false;
    }else{
        lblNomeGrupoPesquisa.setText("Nome do Grupo de Pesquisa");
        lblNomeGrupoPesquisa.setForeground(Color.black);
    }
    
    if(util.isNullOrEmpty(txtAtividadeGrupoPesquisa.getText())){
        lblAtividadeGrupoPesquisa.setText("Atividade do Grupo de Pesquisa*");
        lblAtividadeGrupoPesquisa.setForeground(Color.red);
           
        JOptionPane.showMessageDialog(null, "Preencha o campo Atividade do Grupo de Pesquisa.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
        return false;
    }else{
        lblAtividadeGrupoPesquisa.setText("Atividade do Grupo de Pesquisa");
        lblAtividadeGrupoPesquisa.setForeground(Color.black);
    }
    
    if(util.isNullOrEmpty(txtAreaConhecimento.getText())){
        lblAreaConhecimento.setText("Área de Conhecimento*");
        lblAreaConhecimento.setForeground(Color.red);
           
        JOptionPane.showMessageDialog(null, "Preencha o campo Área de Conhecimento.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
        return false;
    }else{
        lblAreaConhecimento.setText("Área de Conhecimento");
        lblAreaConhecimento.setForeground(Color.black);
    }
    
    if(util.isNullOrEmpty(txtPalavraChave.getText())){
        lblPalavraChave.setText("Palavra-Chave*");
        lblPalavraChave.setForeground(Color.red);
           
        JOptionPane.showMessageDialog(null, "Preencha o campo Palavra-Chave.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
        return false;
    }else{
        lblPalavraChave.setText("Palavra-Chave");
        lblPalavraChave.setForeground(Color.black);
    }
    
    if(util.isNullOrEmpty(txtDescricaoIE.getText())){
        lblDescricaoIE.setText("Descrição de Infra-Estrutura*");
        lblDescricaoIE.setForeground(Color.red);
           
        JOptionPane.showMessageDialog(null, "Preencha o campo Descrição de Infra-Estrutura.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
        return false;
    }else{
        lblDescricaoIE.setText("Descrição de Infra-Estrutura");
        lblDescricaoIE.setForeground(Color.black);
    }
     
    if(util.isNullOrEmpty(txtResultadosEsperados.getText())){
        lblResultadosEsperados.setText("Resultados Esperados*");
        lblResultadosEsperados.setForeground(Color.red);
           
        JOptionPane.showMessageDialog(null, "Preencha o campo Resultados Esperados.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
        return false;
    }else{
        lblResultadosEsperados.setText("Resultados Esperados");
        lblResultadosEsperados.setForeground(Color.black);
    }
    
    if(util.isNullOrEmpty(txtComentariosAdicionais.getText())){
        lblComentariosAdicionais.setText("Comentários Adcionais*");
        lblComentariosAdicionais.setForeground(Color.red);
           
        JOptionPane.showMessageDialog(null, "Preencha o campo Comentários Adicionais.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
        return false;
    }else{
        lblComentariosAdicionais.setText("Comentários Adicionais");
        lblComentariosAdicionais.setForeground(Color.black);
    }
    if(util.isNullOrEmpty(txtResumoAtividades.getText())){
        lblResumoAtividades.setText("Resumo de Atividades*");
        lblResumoAtividades.setForeground(Color.red);
           
        JOptionPane.showMessageDialog(null, "Preencha o campo Resumo de Atividades.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
        return false;
    }else{
        lblResumoAtividades.setText("Resumo de Atividades");
        lblResumoAtividades.setForeground(Color.black);
    }
    
    return true;    
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarGrupoPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarGrupoPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarGrupoPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarGrupoPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarGrupoPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup grupoBotoes;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblAreaConhecimento;
    private javax.swing.JLabel lblAtividadeGrupoPesquisa;
    private javax.swing.JLabel lblComentariosAdicionais;
    private javax.swing.JLabel lblDescricaoIE;
    private javax.swing.JLabel lblInfraEstrutura;
    private javax.swing.JLabel lblNomeGrupoPesquisa;
    private javax.swing.JLabel lblPalavraChave;
    private javax.swing.JLabel lblResultadosEsperados;
    private javax.swing.JLabel lblResumoAtividades;
    private javax.swing.JLabel lblTelaBusca;
    private javax.swing.JRadioButton radioNao;
    private javax.swing.JRadioButton radioSim;
    private javax.swing.JTextField txtAreaConhecimento;
    private javax.swing.JTextField txtAtividadeGrupoPesquisa;
    private javax.swing.JTextField txtComentariosAdicionais;
    private javax.swing.JTextField txtDescricaoIE;
    private javax.swing.JTextField txtNomeGrupoPesquisa;
    private javax.swing.JTextField txtPalavraChave;
    private javax.swing.JTextField txtResultadosEsperados;
    private javax.swing.JTextField txtResumoAtividades;
    // End of variables declaration//GEN-END:variables
}
