/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifba.scop.projetopesquisa.view;

/**
 *
 * @author jonatasfbastos
 */
public class CadastrarProjetoPesquisa extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarProjetoPesquisa
     */
    public CadastrarProjetoPesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        txtCordenador = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTituloProjeto = new javax.swing.JTextField();
        txtSubarea = new javax.swing.JTextField();
        txtLinhaPesquisa = new javax.swing.JTextField();
        chkSim = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        chkNao = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtFonte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jspDataInicio = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jspDataTermino = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLocalDesenvolvimento = new javax.swing.JTextField();
        txtGrupoPesquisa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCampus = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtViabilidadeTecnica = new javax.swing.JTextArea();
        btnCadastrar = new javax.swing.JButton();

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        txtCordenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCordenadorActionPerformed(evt);
            }
        });
        jPanel1.add(txtCordenador);
        txtCordenador.setBounds(30, 110, 303, 27);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(30, 163, 303, 27);
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(30, 216, 182, 29);

        jLabel1.setText("Coordenador(a)");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 90, 77, 14);

        jLabel2.setText("Email");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 143, 24, 14);

        jLabel3.setText("Telefone");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 196, 42, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cadastro de Projeto de pesquisa");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(284, 32, 198, 17);

        jLabel9.setText("Título do projeto");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 251, 79, 14);

        jLabel10.setText("Subárea");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 304, 40, 14);

        jLabel11.setText("Linha de pesquisa");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 357, 85, 14);

        txtTituloProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloProjetoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTituloProjeto);
        txtTituloProjeto.setBounds(30, 271, 303, 27);

        txtSubarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubareaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSubarea);
        txtSubarea.setBounds(30, 324, 303, 27);

        txtLinhaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinhaPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(txtLinhaPesquisa);
        txtLinhaPesquisa.setBounds(30, 377, 303, 27);

        chkSim.setText("Sim");
        chkSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSimActionPerformed(evt);
            }
        });
        jPanel1.add(chkSim);
        chkSim.setBounds(405, 446, 41, 23);

        jLabel5.setText("Financiamento");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(405, 410, 69, 14);

        chkNao.setText("Não");
        jPanel1.add(chkNao);
        chkNao.setBounds(464, 446, 45, 23);

        jLabel6.setText("Fonte");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(405, 304, 28, 14);

        txtFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFonteActionPerformed(evt);
            }
        });
        jPanel1.add(txtFonte);
        txtFonte.setBounds(405, 324, 306, 27);

        jLabel7.setText("Data de inicio");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(405, 225, 64, 14);

        jspDataInicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1578770023278L), null, null, java.util.Calendar.DAY_OF_MONTH));
        jPanel1.add(jspDataInicio);
        jspDataInicio.setBounds(558, 222, 153, 20);

        jLabel8.setText("Data de Término prevista");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(405, 256, 121, 14);

        jspDataTermino.setModel(new javax.swing.SpinnerDateModel());
        jPanel1.add(jspDataTermino);
        jspDataTermino.setBounds(558, 253, 153, 20);

        jLabel12.setText("Grupo de pesquisa");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 410, 89, 14);

        jLabel13.setText("Campus");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 463, 38, 14);

        txtLocalDesenvolvimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalDesenvolvimentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtLocalDesenvolvimento);
        txtLocalDesenvolvimento.setBounds(30, 532, 303, 27);

        txtGrupoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrupoPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(txtGrupoPesquisa);
        txtGrupoPesquisa.setBounds(30, 430, 303, 27);

        jLabel14.setText("Local de desenvolvimento da pesquisa (espaço físico)");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 512, 255, 14);

        txtCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampusActionPerformed(evt);
            }
        });
        jPanel1.add(txtCampus);
        txtCampus.setBounds(30, 479, 303, 27);

        jLabel15.setText("Viabilidade técnica");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(405, 90, 87, 14);

        txtViabilidadeTecnica.setColumns(20);
        txtViabilidadeTecnica.setRows(5);
        jScrollPane1.setViewportView(txtViabilidadeTecnica);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(405, 110, 306, 96);

        btnCadastrar.setText("Cadastrar");
        jPanel1.add(btnCadastrar);
        btnCadastrar.setBounds(551, 587, 160, 27);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 830, 683));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void txtCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampusActionPerformed

    private void txtGrupoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrupoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrupoPesquisaActionPerformed

    private void txtLocalDesenvolvimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalDesenvolvimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalDesenvolvimentoActionPerformed

    private void txtFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFonteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFonteActionPerformed

    private void chkSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSimActionPerformed

    private void txtLinhaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinhaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinhaPesquisaActionPerformed

    private void txtSubareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubareaActionPerformed

    private void txtTituloProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloProjetoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCordenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCordenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCordenadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProjetoPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProjetoPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProjetoPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProjetoPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProjetoPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JCheckBox chkNao;
    private javax.swing.JCheckBox chkSim;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JSpinner jspDataInicio;
    private javax.swing.JSpinner jspDataTermino;
    private javax.swing.JTextField txtCampus;
    private javax.swing.JTextField txtCordenador;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFonte;
    private javax.swing.JTextField txtGrupoPesquisa;
    private javax.swing.JTextField txtLinhaPesquisa;
    private javax.swing.JTextField txtLocalDesenvolvimento;
    private javax.swing.JTextField txtSubarea;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTituloProjeto;
    private javax.swing.JTextArea txtViabilidadeTecnica;
    // End of variables declaration//GEN-END:variables
}
